import AppKit

/// The selectors Sion's menus send, resolved by name so the responder that
/// implements one does not have to be visible from where the menu is built.
///
/// The main menu and the canvas's contextual menu send the same commands, so
/// they name them in the same place: a command that moves keeps working from
/// both, and one that is renamed stops compiling in both.
enum AppAction {
  static let actualSize = Selector(("actualSize:"))
  static let addSelectionToDocumentLibrary = Selector(("addSelectionToDocumentLibrary:"))
  static let addSelectionToGlobalLibrary = Selector(("addSelectionToGlobalLibrary:"))
  static let alignBottom = Selector(("alignBottom:"))
  static let alignCenterHorizontally = Selector(("alignCenterHorizontally:"))
  static let alignCenterVertically = Selector(("alignCenterVertically:"))
  static let alignLeading = Selector(("alignLeading:"))
  static let alignTop = Selector(("alignTop:"))
  static let alignTrailing = Selector(("alignTrailing:"))
  static let bringForward = Selector(("bringForward:"))
  static let bringToFront = Selector(("bringToFront:"))
  static let close = Selector(("performClose:"))
  static let copy = Selector(("copy:"))
  static let cut = Selector(("cut:"))
  static let delete = Selector(("delete:"))
  static let distributeHorizontally = Selector(("distributeHorizontally:"))
  static let distributeVertically = Selector(("distributeVertically:"))
  static let duplicate = Selector(("duplicate:"))
  static let exportImage = Selector(("exportImage:"))
  static let exportMermaid = Selector(("exportMermaid:"))
  static let exportSVG = Selector(("exportSVG:"))
  static let hideSelection = Selector(("hideSelection:"))
  static let importMermaid = Selector(("importMermaid:"))
  static let lockSelection = Selector(("lockSelection:"))
  static let newDocumentFromMermaid = Selector(("newDocumentFromMermaid:"))
  static let pageSetup = #selector(NSDocument.runPageLayout(_:))
  static let paste = Selector(("paste:"))
  static let printDocument = #selector(NSDocument.printDocument(_:))
  static let redo = Selector(("redo:"))
  static let revealHiddenElements = Selector(("revealHiddenElements:"))
  static let revertToSaved = #selector(NSDocument.revertToSaved(_:))
  static let save = Selector(("saveDocument:"))
  static let saveAs = Selector(("saveDocumentAs:"))
  static let selectAll = Selector(("selectAll:"))
  static let sendBackward = Selector(("sendBackward:"))
  static let sendToBack = Selector(("sendToBack:"))
  static let showHistory = Selector(("showHistory:"))
  static let showInspector = Selector(("showInspector:"))
  static let showLibrary = Selector(("showLibrary:"))
  static let toggleGridVisibility = Selector(("toggleGridVisibility:"))
  static let toggleObjectSnapping = Selector(("toggleObjectSnapping:"))
  static let undo = Selector(("undo:"))
  static let unlockSelection = Selector(("unlockSelection:"))
  static let zoomIn = Selector(("zoomIn:"))
  static let zoomOut = Selector(("zoomOut:"))
  static let zoomToFit = Selector(("zoomToFit:"))
}
